name: mini-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.25.0
      - langchain>=0.0.267
      - langchain-core>=0.1.4
      - langchain-community>=0.0.12
      - langgraph>=0.0.21
      - qdrant-client>=1.6.3
      - sentence-transformers>=2.2.2
      - torch>=2.0.0
      - PyPDF2>=3.0.0
      - pypdf>=5.3.1
      - pdf2image>=1.16.3
      - docx2txt>=0.8
      - python-docx>=0.8.11
      - transformers>=4.36.0
      - huggingface-hub>=0.17.3
      - python-dotenv>=1.0.0
      - uuid>=1.30
      - fuzzywuzzy>=0.18.0
      - Crawl4AI>=0.5.0
      - unstructured[md]>=0.16.25
      # - logging>=0.5.1
